# Generated by Django 3.1 on 2020-08-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='defined_term',
            new_name='definition_term',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='defined_text',
            new_name='definition_text',
        ),
    ]
